SQUADS = {
    "Pakistan": [
        "Babar Azam",
        "Abdullah Shafique",
        "Imam-ul-Haq",
        "Saud Shakeel",
        "Mohammad Rizwan",
        "Salman Ali Agha",
        "Shan Masood",
        "Saim Ayub",
        "Mohammad Nawaz",
        "Noman Ali",
        "Sajid Khan",
        "Mohammad Abbas",
        "Mohammad Ali",
        "Shaheen Shah Afridi",
    ],
    "England": [
        "Joe Root",
        "Ben Duckett",
        "Zak Crawley",
        "Harry Brook",
        "Ollie Pope",
        "Dan Lawrence",
        "Jamie Smith",
        "Jacob Bethell",
        "Brydon Carse",
        "Jofra Archer",
        "Gus Atkinson",
        "Josh Tongue",
        "Shoaib Bashir",
        "Ollie Robinson",
    ],
    "India": [
        "Rohit Sharma",
        "Shubman Gill",
        "Virat Kohli",
        "Yashasvi Jaiswal",
        "Shreyas Iyer",
        "KL Rahul",
        "Rishabh Pant",
        "Ravindra Jadeja",
        "Axar Patel",
        "Kuldeep Yadav",
        "Mohammed Shami",
        "Jasprit Bumrah",
        "Mohammed Siraj",
        "Washington Sundar",
    ],
    "Australia": [
        "David Warner",
        "Travis Head",
        "Marnus Labuschagne",
        "Steve Smith",
        "Cameron Green",
        "Mitchell Marsh",
        "Alex Carey",
        "Pat Cummins",
        "Mitchell Starc",
        "Josh Hazlewood",
        "Adam Zampa",
        "Nathan Lyon",
        "Glenn Maxwell",
        "Marcus Stoinis",
    ],
    "South Africa": [
        "Temba Bavuma",
        "Aiden Markram",
        "Tony de Zorzi",
        "Rassie van der Dussen",
        "David Miller",
        "Heinrich Klaasen",
        "Marco Jansen",
        "Wiaan Mulder",
        "Kagiso Rabada",
        "Anrich Nortje",
        "Lungi Ngidi",
        "Keshav Maharaj",
        "Tabraiz Shamsi",
        "Quinton de Kock",
    ],
    "New Zealand": [
        "Devon Conway",
        "Will Young",
        "Kane Williamson",
        "Rachin Ravindra",
        "Daryl Mitchell",
        "Tom Latham",
        "Glenn Phillips",
        "Mitchell Santner",
        "Michael Bracewell",
        "Kyle Jamieson",
        "Tim Southee",
        "Trent Boult",
        "Lockie Ferguson",
        "Matt Henry",
    ],
    "Sri Lanka": [
        "Pathum Nissanka",
        "Dimuth Karunaratne",
        "Kusal Mendis",
        "Kusal Perera",
        "Sadeera Samarawickrama",
        "Charith Asalanka",
        "Dhananjaya de Silva",
        "Dasun Shanaka",
        "Wanindu Hasaranga",
        "Maheesh Theekshana",
        "Dushmantha Chameera",
        "Dilshan Madushanka",
        "Kasun Rajitha",
        "Angelo Mathews",
    ],
    "West Indies": [
        "Brandon King",
        "Kyle Mayers",
        "Johnson Charles",
        "Shai Hope",
        "Nicholas Pooran",
        "Shimron Hetmyer",
        "Rovman Powell",
        "Jason Holder",
        "Alzarri Joseph",
        "Shamar Joseph",
        "Gudakesh Motie",
        "Akeal Hosein",
        "Romario Shepherd",
        "Sherfane Rutherford",
    ],
}